on:
  push:
    branches:
      - main
  workflow_dispatch:
name: Deploy website on main push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3
      - run: yarn install && yarn build

      - name: Sync files  
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{ secrets.FTP }}  
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: './dist/' 
          remoteDir: './www/' 
          exclude: '.git*,**/.git*,**/.git*/**,**/.idea*,**/.idea*/**.DS_Store' 
